mod.id=stackablepotions
mod.name=Stackable Potions
mod.group=cursedflames
mod.version=1.0.0
mod.author=CursedFlames
mod.license=MIT
mod.description=Allows vanilla potions to stack.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/StackablePotions
mod.homepage_url=https://modrinth.com/mod/stackablepotions
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=stackablepotions
publish.curseforge.fabric=396596
publish.curseforge.neoforge=599436
