mod.id=hopperbucket
mod.name=Hopper Bucket
mod.group=cursedflames
mod.version=1.0.2
mod.author=CursedFlames
mod.license=MIT
mod.description=Allows hoppers containing buckets to remove and add fluids from the world.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/HopperBucket
mod.homepage_url=https://modrinth.com/mod/hopper-bucket
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=hopper-bucket
publish.curseforge=885043
