org.gradle.jvmargs=-Xmx16G
org.gradle.parallel=true
# Stop sitting around eating all my RAM you asshole
org.gradle.daemon=false
# Setting this to false might make intellij stop freaking out? unsure
org.gradle.configuration-cache=false

deps.fabric-loader=0.18.4
deps.fabric-loom=1.15-SNAPSHOT
deps.moddev=2.0.115

# Apparently helps with performance when multiple subprojects are using loom
fabric.loom.multiProjectOptimisation=true
