#!/usr/bin/env bash

# Check both staged and unstaged changes
if git diff --name-only | grep -q "^\.sc_active_version$" || git diff --name-only --staged | grep -q "^\.sc_active_version$"; then
  echo 'Remember to reset the active stonecutter version ("Reset active project") before commit!'
  echo "To ignore this check (i.e. when changing the default version) use git commit --no-verify"
  exit 1
fi
