mod.id=fasttoolswitching
mod.name=Fast Tool Switching
mod.group=cursedflames
mod.version=1.0.0
mod.author=CursedFlames
mod.license=MIT
mod.description=Stops players' attack cooldown from resetting when they switch items.\nThe time since last attack is retained, so this cannot be exploited by attacking with a quick weapon then switching to an item with a longer cooldown. (The full cooldown will still apply)

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/FastToolSwitching
mod.homepage_url=https://modrinth.com/mod/fast-tool-switching
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=fast-tool-switching
publish.curseforge.neoforge=348495
publish.curseforge.fabric=599423
