mod.id=nametaggableplayers
mod.name=NametaggablePlayers
mod.group=cursedflames
mod.version=1.0.0
mod.author=CursedFlames
mod.license=MIT
mod.description=Allows nametags to be used on players - depending on config you can rename yourself, other players, or both.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/NametaggablePlayers
mod.homepage_url=
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=8HVdVYoa
publish.curseforge=1494694

deps.fzzy-config.enabled=1
