mod.id=modtemplate
mod.name=Mod Template
mod.group=dev.spagurder
mod.version=0.1.0
mod.author=AuthorName
mod.license=ARR
mod.description=Example Description

mod.sources_url=https://example.com/sources_url
mod.homepage_url=https://example.com/homepage_url
mod.issues_url=https://example.com/issues_url

publish.modrinth=
publish.curseforge=
