mod.id=updatingworldicon
mod.name=Updating World Icon
mod.group=cursedflames
mod.version=1.0.1
mod.author=CursedFlames
mod.license=MIT
mod.description=Makes the singleplayer world icon regenerate each time the world is loaded, instead of keeping the first icon forever.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/UpdatingWorldIcon
mod.homepage_url=https://modrinth.com/mod/updating-world-icon
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=ZlX3EVmE
publish.curseforge=885046
