mod.id=noincreasingrepaircost
mod.name=No Increasing Repair Cost
mod.group=cursedflames
mod.version=1.0.0
mod.author=CursedFlames
mod.license=MIT
mod.description=Disables the increasing repair/enchant cost on items in anvils.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/NoIncreasingRepairCost
mod.homepage_url=https://modrinth.com/mod/no-increasing-repair-cost
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=LyBfWHkb
publish.curseforge=349910
