mod.id=pale
mod.name=Pale
mod.group=cursedflames
mod.version=1.0.1
mod.author=CursedFlames
mod.license=MIT
mod.description=Makes rotten flesh inflict Pale, a status effect that causes damage in sunlight, instead of Hunger.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/Pale
mod.homepage_url=https://modrinth.com/mod/pale-mod
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=MRcaABcr
publish.curseforge=419573
