modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"
${issues_url}

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
${homepage_url}
logoFile = "icon.png"
authors = "${author}"
logoBlur = false
${contributors}

description = '''${description}'''

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft}]"
