mod.id=splitshulkers
mod.name=Split Shulker Boxes
mod.group=cursedflames
mod.version=1.0.1
mod.author=CursedFlames
mod.license=MIT
mod.description=Allows you to dye the top and bottom half of shulker boxes independently\n\n(The position of the dye within the crafting recipe determines which side(s) are dyed)

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/SplitShulkerBoxes
mod.homepage_url=https://modrinth.com/mod/split-shulker-boxes
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=split-shulker-boxes
publish.curseforge=887284
