mod.id=nodurability
mod.name=No Durability
mod.group=cursedflames
mod.version=1.0.0
mod.author=CursedFlames
mod.license=MIT
mod.description=Completely remove item durability from the game.

mod.sources_url=https://github.com/CursedFlames/MCTweaks/tree/stonecutter/NoDurability
mod.homepage_url=https://modrinth.com/mod/modifiers
mod.issues_url=https://github.com/CursedFlames/MCTweaks/issues

publish.modrinth=non-durability
publish.curseforge=420724
